graph:
  batch_size: 128

  lr:
    min: 1.0e-6
    max: 1.0e-1

  n_epochs: 50

  embedding_dim:
    min: 64
    max: 1024

  hidden_dim:
    min: 512
    max: 4096

  dataset_path: data/droparray_full.pt

  n_trials: 50

trimnet:
  batch_size: 128

  lr:
    min: 1.0e-6
    max: 1.0e-1

  n_epochs: 50

  hidden_dim:
    min: 512
    max: 4096

  dataset_path: data/droparray_full.pt

  n_trials: 50

3d_infomax:
  batch_size: 128

  lr:
    min: 1.0e-6
    max: 1.0e-1

  n_epochs: 50

  hidden_dim:
    min: 512
    max: 4096

  dataset_path: data/droparray_full.pt

  n_trials: 50
