batch_size: [32, 64, 128]
lr: [0.005, 0.001, 0.0005]
n_epochs: [50, 100, 200]
embedding_dim: [64, 128, 256]
hidden_dim: [128, 256, 512]
dataset_path: data/torch_small_reduced.pt
vectorized_dataset_path: lll.pt
