graph:
  batch_size:
    min: 32
    max: 512

  lr:
    min: 1.0e-6
    max: 1.0e-1

  n_epochs:
    min: 5
    max: 10

  embedding_dim:
    min: 64
    max: 1024

  hidden_dim:
    min: 512
    max: 4096

  dataset_path: data/debug_dataset.pt

  n_trials: 2

trimnet:
  batch_size:
    min: 32
    max: 512

  lr:
    min: 1.0e-6
    max: 1.0e-1

  n_epochs:
    min: 5
    max: 10

  hidden_dim:
    min: 512
    max: 4096

  dataset_path: data/debug_dataset.pt

  n_trials: 2

3d_infomax:
  batch_size:
    min: 32
    max: 512

  lr:
    min: 1.0e-6
    max: 1.0e-1

  n_epochs:
    min: 5
    max: 10

  hidden_dim:
    min: 512
    max: 4096

  dataset_path: data/debug_dataset.pt

  n_trials: 2
