name: drugpred_da

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - pytorch-cuda=12.1
  - rdkit
